<!DOCTYPE html>
<html>
<head>
<title>Руководство пользователя</title>
<hta:application
id="MyApp"
applicationname="Руководство пользователя"/>
<style>
div {
border: 2px solid black;
margin: 0.25cm;
padding: 0.25cm;
border-radius: 15px;
}
</style>
</head>
<body>
<div>
<h1>Титульный экран</h1>
<div>
<h2>Создание нового файла</h2>
<p>Позволяет пользователям создавать новые файлы для хранения заметок.</p>
<p>Действия:</p>
<ol>
<li>На титульном экране нажмите кнопку "Создать новый файл".</li>
<li>Выберите тип файла (заметки, документ, список дел и т.д.).</li>
<li>Введите название файла.</li>
<li>Нажмите кнопку "Создать", чтобы завершить процесс.</li>
</ol>
</div>
<div>
<h2>Открытие существующего файла</h2>
<p>Позволяет пользователям открывать уже существующие файлы с заметками для дальнейшего редактирования.</p>
<p>Действия:</p>
<ol>
<li>На титульном экране выберите "Открыть файл".</li>
<li>Просмотрите список доступных файлов или воспользуйтесь поиском.</li>
<li>Выберите нужный файл и нажмите "Открыть".</li>
</ol>
</div>
<div>
<h2>Экспорт текущего файла</h2>
<p>Обеспечивает возможность экспорта текущего файла с заметками в различные форматы для обмена или публикации.</p>
<p>Действия:</p>
<ol>
<li>Откройте файл, который вы хотите экспортировать.</li>
<li>На панели инструментов или в меню выберите "Экспорт".</li>
<li>Выберите формат экспорта (PDF, XPS, DOCX и т.д.).</li>
<li>Укажите необходимые параметры (если есть) и нажмите "Экспортировать".</li>
</ol>
</div>
<div>
<h2>Настройки</h2>
<p>Предоставляет пользователю доступ к настройкам приложения, позволяя настраивать его поведение и интерфейс.</p>
<ul>
<li>Изменение темы оформления.</li>
<li>Настройка шрифтов и размеров.</li>
<li>Управление уведомлениями и звуками.</li>
<li>Настройка расположения элементов интерфейса.</li>
</ul>
<p>Для изменения настроек:</p>
<ol>
<li>На титульном экране выберите "Настройки" или иконку шестеренки.</li>
<li>Измените необходимые параметры.</li>
<li>Нажмите "Сохранить" или "Применить", чтобы применить изменения.</li>
</ol>
</div>
</div>
<div>
<h1>Записная книга</h1>
<div>
<h2>Дерево разделов</h2>
<p>Дерево разделов представляет собой основу организации заметок в записной книге. Здесь пользователь может управлять
разделами, группировать их для удобства и быстрого доступа к нужным заметкам.</p>
<div>
<h3>Раздел</h3>
<p>Представляет собой отдельный раздел в дереве разделов, содержащий его название, цвет закладки и ссылку на
соответствующую страницу с заметками.</p>
<p>Действия:</p>
<ol>
<li>Нажмите на раздел, чтобы перейти к списку заметок внутри него.</li>
<li>Установите цвет закладки для раздела, чтобы легко его найти и отличить от других.</li>
</ol>
</div>
<div>
<h3>Группа разделов</h3>
<p>Группирует разделы для более удобной навигации и организации заметок, содержит название группы разделов и список
разделов, входящих в нее.</p>
<p>Действия:</p>
<ol>
<li>Создайте новую группу разделов, выбрав опцию "Создать группу".</li>
<li>Добавьте разделы в группу, перетащив их внутрь нее.</li>
</ol>
</div>
<div>
<h3>Редактирование списка разделов</h3>
<p>Позволяет пользователю редактировать список разделов, включая добавление, удаление и перемещение разделов для более
удобной организации заметок.</p>
<p>Действия:</p>
<ol>
<li>На экране дерева разделов выберите "Редактировать список разделов".</li>
<li>Добавьте новые разделы, нажав на кнопку "Добавить", и введите название.</li>
<li>Для удаления раздела выберите его и нажмите "Удалить".</li>
<li>Перемещайте разделы, удерживая их и перетаскивая в нужное место.</li>
</ol>
</div>
<div>
<h3>Отображение дерева разделов</h3>
<p>Обеспечивает отображение дерева разделов в интерфейсе приложения, что упрощает навигацию и выбор нужного раздела.</p>
<p>Действия:</p>
<ol>
<li>На главном экране записной книги отобразится дерево разделов.</li>
<li>Кликните по разделу или группе, чтобы развернуть или свернуть список заметок.</li>
</ol>
</div>
</div>
<div>
<h2>Страница</h2>
<p>Страница в записной книге представляет собой основное рабочее пространство, на котором пользователь может создавать и
хранить заметки различного типа.</p>
<div>
<h3>Отображение блоков</h3>
<p>Предоставляет области для содержимого заметок на странице, которые могут иметь разную форму и располагаться в разных частях страницы.</p>
<p>Действия:</p>
<ol>
<li>Выберите тип блока (текстовая заметка, графический элемент, таблица и т.д.).</li>
<li>Перетащите и расположите блоки на странице в нужном порядке.</li>
</ol>
</div>
<div>
<h3>Текстовые заметки</h3>
<p>Позволяет пользователю создавать и редактировать текстовые заметки на странице.</p>
<p>Действия:</p>
<ol>
<li>Кликните на область страницы, чтобы начать печатать текст.</li>
<li>Используйте инструменты редактирования для форматирования текста.</li>
</ol>
<div>
<h4>Редактирование шрифта</h4>
<p>Позволяет пользователю редактировать размер и тип шрифта текстовых заметок, изменяя их внешний вид.</p>
<p>Действия:</p>
<ol>
<li>Выделите текст, который нужно изменить.</li>
<li>Используйте панель инструментов для выбора размера, стиля и цвета шрифта.</li>
</ol>
</div>
<div>
<h4>Копирование форматирования</h4>
<p>Обеспечивает возможность копирования форматирования текстовых заметок между различными блоками на странице.</p>
<p>Действия:</p>
<ol>
<li>Выберите текст с нужным форматированием.</li>
<li>Используйте опцию "Копировать формат" и примените его к другому блоку.</li>
</ol>
</div>
<div>
<h4>Редактирование списков</h4>
<p>Позволяет пользователю создавать и редактировать списки в текстовых заметках для организации информации.</p>
<p>Действия:</p>
<ol>
<li>Выберите опцию "Создать список" из панели инструментов.</li>
<li>Добавляйте элементы списка, нажимая Enter.</li>
</ol>
</div>
</div>
<div>
<h3>Графические заметки</h3>
<p>Позволяет пользователю добавлять и редактировать графические элементы на странице, такие как изображения и рисунки.</p>
<div>
<h4>Импорт изображений</h4>
<p>Позволяет пользователю добавлять существующие изображения на страницу в качестве графических заметок.</p>
<p>Действия:</p>
<ol>
<li>Выберите опцию "Импорт изображения".</li>
<li>Выберите файл изображения на компьютере и добавьте на страницу.</li>
</ol>
</div>
<div>
<h4>Создание произвольных изображений</h4>
<p>Предоставляет возможность пользователю создавать рисунки и изображения непосредственно на странице с помощью ручного рисования.</p>
<p>Действия:</p>
<ol>
<li>Выберите инструмент "Ручка" или "Кисть".</li>
<li>Начните рисовать на странице с помощью мыши или стилуса.</li>
</ol>
</div>
<div>
<h4>Редактирование изображений</h4>
<p>Позволяет пользователю редактировать добавленные изображения, включая их обрезку или дополнительное рисование поверх них.</p>
<p>Действия:</p>
<ol>
<li>Выберите изображение на странице.</li>
<li>Используйте инструменты редактирования для изменения размера, обрезки или рисования поверх него.</li>
</ol>
</div>
</div>
<div>
<h3>Сложные объекты</h3>
<p>Предоставляет возможность добавления на страницу различных сложных объектов, таких как таблицы, диаграммы, уравнения и другие.</p>
<div>
<h4>Редактор таблиц</h4>
<p>Позволяет пользователю создавать и редактировать таблицы на странице для организации данных в табличной форме.</p>
<p>Действия:</p>
<ol>
<li>Выберите опцию "Добавить таблицу".</li>
<li>Выберите количество строк и столбцов, затем заполните таблицу.</li>
</ol>
</div>
<div>
<h4>Редактор диаграмм</h4>
<p>Обеспечивает возможность создания и редактирования диаграмм различных типов для визуализации данных на странице.</p>
<p>Действия:</p>
<ol>
<li>Выберите тип диаграммы (круговая, столбчатая и т.д.).</li>
<li>Введите данные или импортируйте их из таблицы.</li>
</ol>
</div>
<div>
<h4>Редактор уравнений</h4>
<p>Позволяет пользователю создавать и редактировать математические уравнения на странице с помощью специального редактора.</p>
<p>Действия:</p>
<ol>
<li>Выберите опцию "Добавить уравнение".</li>
<li>Используйте математические символы и инструменты для создания уравнения.</li>
</ol>
</div>
<div>
<h4>Импорт бинарных файлов</h4>
<p>Позволяет добавлять на страницу ссылки на бинарные файлы с возможностью их экспорта и просмотра.</p>
<p>Действия:</p>
<ol>
<li>Выберите опцию "Добавить файл".</li>
<li>Загрузите бинарный файл с компьютера.</li>
</ol>
</div>
<div>
<h4>Импорт файлов-документов</h4>
<p>Позволяет пользователю импортировать файлы документов различных форматов (например, DOCX, PDF) на страницу в виде распечаток.</p>
<p>Действия:</p>
<ol>
<li>Выберите опцию "Импорт документа".</li>
<li>Загрузите файл документа и выберите способ отображения на странице.</li>
</ol>
</div>
<div>
<h4>Редактор ссылок на интернет-источники</h4>
<p>Позволяет пользователю создавать и редактировать ссылки на интернет-источники прямо на странице.</p>
<p>Действия:</p>
<ol>
<li>Выделите текст для ссылки.</li>
<li>Нажмите на опцию "Добавить ссылку" и введите URL.</li>
</ol>
</div>
<div>
<h4>Запись звука микрофона</h4>
<p>Обеспечивает возможность записи звуков с микрофона и добавления их на страницу в качестве аудиозаметок.</p>
<p>Действия:</p>
<ol>
<li>Нажмите на опцию "Записать звук".</li>
<li>Начните запись звука, затем сохраните на странице.</li>
</ol>
</div>
<div>
<h4>Запись экрана монитора</h4>
<p>Позволяет пользователю записывать видео с экрана монитора и добавлять его на страницу в качестве видеозаметок.</p>
<p>Действия:</p>
<ol>
<li>Выберите опцию "Записать экран".</li>
<li>Начните запись видео, затем сохраните на странице.</li>
</ol>
</div>
</div>
<div>
<h3>Теги</h3>
<p>Позволяют классифицировать блоки заметок с помощью тегов для более удобного поиска и организации информации.</p>
<div>
<h4>Редактирование тегов</h4>
<p>Позволяет пользователю создавать, редактировать и удалять теги для классификации своих заметок.</p>
<p>Действия:</p>
<ol>
<li>Нажмите на блок заметки с тегом.</li>
<li>Выберите опцию "Редактировать теги" для изменения или удаления тегов.</li>
</ol>
</div>
<div>
<h4>Поиск заметок по тегам</h4>
<p>Обеспечивает возможность быстрого поиска заметок по их тегам для удобной навигации по записной книге.</p>
<p>Действия:</p>
<ol>
<li>Введите ключевое слово тега в поле поиска.</li>
<li>Просмотрите результаты поиска и выберите нужную заметку.</li>
</ol>
</div>
</div>
<div>
<h3>Стили страницы</h3>
<p>Позволяют пользователю настраивать внешний вид страницы, включая цвет фона, сетку и масштаб отображения.</p>
<div>
<h4>Редактирование цвета фона</h4>
<p>Позволяет пользователю выбирать и изменять цвет фона страницы для создания комфортной рабочей обстановки.</p>
<p>Действия:</p>
<ol>
<li>Выберите опцию "Изменить цвет фона".</li>
<li>Выберите цвет из палитры или введите свой.</li>
</ol>
</div>
<div>
<h4>Добавление сетки</h4>
<p>Обеспечивает возможность добавления сетки или линий на фон страницы для удобства выравнивания элементов.</p>
<p>Действия:</p>
<ol>
<li>Выберите опцию "Добавить сетку".</li>
<li>Выберите стиль и шаг сетки для отображения.</li>
</ol>
</div>
<div>
<h4>Изменение масштаба отображения</h4>
<p>Позволяет пользователю изменять масштаб отображения содержимого страницы для лучшего просмотра и работы.</p>
<p>Действия:</p>
<ol>
<li>Используйте ползунок масштаба на панели инструментов.</li>
<li>Измените масштаб отображения по вашему усмотрению.</li>
</ol>
</div>
</div>
<div>
<h3>Журналирование</h3>
<p>Предоставляет пользователю инструменты для отслеживания всех изменений, внесенных в записную книгу, а также для контроля версий и поиска изменений по автору.</p>
<div>
<h4>Сохранение списка изменений</h4>
<p>Автоматически ведет лог всех изменений, внесенных в записную книгу, для последующего просмотра и восстановления.</p>
</div>
<div>
<h4>Контроль версий</h4>
<p>Обеспечивает возможность восстановления предыдущих версий книги и контроля изменений для обеспечения безопасности данных пользователя.</p>
<p>Действия:</p>
<ol>
<li>Выберите пункт "Журналирование".</li>
<li>Выберите нужную версию документа для восстановления.</li>
</ol>
</div>
<div>
<h4>Поиск изменений по автору</h4>
<p>Позволяет пользователю фильтровать список изменений по автору, чтобы быстро найти изменения, сделанные конкретным пользователем.</p>
<p>Действия:</p>
<ol>
<li>В окне выбора версии документа введите имя пользователя для поиска.</li>
<li>Выберите версию документа из всех версий, созданных искомым пользователем.</li>
</ol>
</div>
</div>
<div>
<h3>Рецензирование</h3>
<p>Предоставляет инструменты для проверки и редактирования содержимого заметок, а также для защиты страниц паролем</p>
<div>
<h4>Проверка читаемости</h4>
<p>Автоматически анализирует содержимое страницы на наличие нечитаемых зон, что помогает улучшить качество заметок. При нахождении плохо-читаемой заметки, оповестит всплывающим уведомлением возле этой заметки.</p>
</div>
<div>
<h4>Проверка орфографии текстовых заметок</h4>
<p>Обеспечивает автоматическую проверку орфографии текстовых заметок и предлагает исправления для найденных ошибок. Найденные ошибки выделяются заметным цветом.</p>
</div>
<div>
<h4>Перевод текстовых данных</h4>
<p>Позволяет пользователю переводить текстовые данные с одного языка на другой с использованием встроенных инструментов
перевода.</p>
<p>Действия:</p>
<ol>
<li>Выберите текстовую заметку и нажмите по ней правой кнопкой мыши.</li>
<li>В контекстном меню выберите группу "Перевод". В выпадающем списке выберите нужный язык.</li>
</ol>
</div>
<div>
<h4>Защита страниц паролем</h4>
<p>Обеспечивает безопасность данных путем добавления пароля для доступа к странице, что помогает защитить конфиденциальную
информацию пользователя.</p>
</div>
</div>
</div>
</div>
<div>
<h1>Отображение окон</h1>
<p>Модуль отображения окон позволяет пользователю эффективно работать с несколькими страницами одновременно, создавая новые окна, закрепляя их поверх других и используя мини-окно для быстрого создания заметок</p>
<div>
<h2>Создание нового окна</h2>
<p>Позволяет пользователям создавать новые окна для работы с двумя или более страницами одновременно, повышая производительность и удобство использования приложения.</p>
<p>Действия:</p>
<ol>
<li>Нажмите на опцию "Создать новое окно" в меню или панели инструментов.</li>
<li>Выберите страницу, которую хотите открыть в новом окне.</li>
<li>Новое окно откроется, позволяя вам работать параллельно с другими страницами.</li>
</ol>
</div>
<div>
<h2>Закрепление окна поверх других</h2>
<p>Обеспечивает возможность закрепления окна поверх других, что позволяет пользователю удобно работать с несколькими окнами одновременно, не теряя нужной информации.</p>
<p>Действия:</p>
<ol>
<li>Выберите окно, которое хотите закрепить поверх других.</li>
<li>Нажмите на опцию "Закрепить окно" в верхнем правом углу окна.</li>
<li>Окно останется на верхнем уровне, даже если вы переключитесь на другое окно.</li>
</ol>
</div>
<div>
<h2>Мини-окно для быстрого создания заметки</h2>
<p>Предоставляет мини-окно, доступное из панели инструментов, для быстрого создания заметок без необходимости переключения между разделами.</p>
<p>Действия:</p>
<ol>
<li>Нажмите на иконку "Мини-окно создания заметки" на панели инструментов.</li>
<li>Мини-окно появится на экране, позволяя вам быстро ввести текст или содержимое заметки.</li>
<li>Нажмите "Сохранить", чтобы добавить заметку в текущее окно или выберите окно, в которое хотите добавить заметку.</li>
</ol>
</div>
</div>
</body>
</html>

